general:
  base_dir: "/export/data/ablattma/neural_pose_behavior/"
  debug: False
  mode: train  # train or infer
  project_name: "train_vunet" # if project name is already existing and not restart_from_checkpoint or infer, then an error is thrown
  restart: False
  experiment: vunet
  seed: 42

data:
  dataset: DeepFashion
  use_person_split: True
  small_joint_model: True
  seq_length: !!python/tuple [0,0]
  sequential_frame_lag: 1
  label_type: velocity # ["mixed","health","velocity","person_id","action","random_pose_action",]
  all_actions: True
  action_split_type: default # [default,generalize_sitting,generalize_walking]
  keypoint_type: keypoints_3d_world # ["angle_world_expmap", "keypoints_3d_world", "keypoints"]
  n_data_workers: 0
  train_synthesis: True
  use_3d_for_stickman: True
  use_crops: False
  inplane_normalize: True
  diff_stickman_colors: False
  spatial_size: 256
  box_factor: 2
  bottleneck_factor: 2
  crop_app: False
  sampling: none # should be in [none, body, full, pid]

architecture:
  n_latent_scales: 2
  conv_layer_type: l1 # [l1,l2]
  nf_start: 32
  nf_max: 128
  subpixel_upsampling: True
  n_scales: 0
  n_rnb: 2

training:
  gpu: 0
  batch_size: 8
  vgg_weights:
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
    - 1.0
  dropout_prob: 0.05
  lr: 0.0008
  kl_init: 0.000001
  kl_max: 1.
  gamma_step: 0.00001
  n_init_batches: 4
  adam_betas: !!python/tuple [0.5,0.9]
  end_iteration: 300000
  ll_weight: 5.
  lr_decay_begin: 1000


metrics:
  test_batch_size: 8
  max_n_samples: 20 # 8000
  n_it_metrics: 20 # 20000

logging:
  n_test_samples: 4
  ckpt_steps: 20 # 1000
  log_steps: 20 # 300
  n_logged_img: 4